#!/usr/bin/env python3
"""Install four geometric triangles for Ghostty's native tmux arrow mapping."""

import argparse
import datetime
import io
import os
from pathlib import Path
import tempfile

from fontTools.fontBuilder import FontBuilder
from fontTools.pens.ttGlyphPen import TTGlyphPen


FAMILY = "Tmux Solid Triangles"
DESTINATION = Path.home() / "Library/Fonts/TmuxSolidTriangles.ttf"
# Match PragmataPro Mono Liga's em, advance and baseline metrics. All polygons
# stay inside one horizontal cell; they contain no third-party font outlines.
ARROWS = {
    0x2190: ("left", ((0, 612), (920, -9), (920, 1233))),
    0x2191: ("up", ((0, 56), (512, 1234), (1024, 56))),
    0x2192: ("right", ((104, -9), (1024, 612), (104, 1233))),
    0x2193: ("down", ((0, 1164), (1024, 1164), (512, -14))),
}


def font_bytes():
    builder = FontBuilder(2048, isTTF=True)
    order = [".notdef", *(name for name, _ in ARROWS.values())]
    glyphs = {".notdef": TTGlyphPen(None).glyph()}
    metrics = {".notdef": (1024, 0)}
    for name, points in ARROWS.values():
        pen = TTGlyphPen(None)
        pen.moveTo(points[0])
        for point in points[1:]:
            pen.lineTo(point)
        pen.closePath()
        glyphs[name] = pen.glyph()
        metrics[name] = (1024, min(x for x, _ in points))
    builder.setupGlyphOrder(order)
    builder.setupCharacterMap({codepoint: name for codepoint, (name, _) in ARROWS.items()})
    builder.setupGlyf(glyphs)
    builder.setupHorizontalMetrics(metrics)
    builder.setupHorizontalHeader(ascent=1884, descent=-362, lineGap=0)
    builder.setupNameTable({
        "familyName": FAMILY,
        "styleName": "Regular",
        "uniqueFontIdentifier": "TmuxSolidTriangles-Regular-1.0",
        "fullName": FAMILY + " Regular",
        "psName": "TmuxSolidTriangles-Regular",
        "version": "Version 1.0",
        "copyright": "Geometric glyphs generated by the local dotfiles repository.",
    })
    builder.setupOS2(sTypoAscender=1526, sTypoDescender=-353, sTypoLineGap=0,
                     usWinAscent=1884, usWinDescent=362, sxHeight=1132, sCapHeight=1526)
    builder.setupPost(isFixedPitch=1)
    builder.setupMaxp()
    # Stable bytes avoid invalidating the system's font cache on every install.
    created = int(datetime.datetime(2026, 10, 6, tzinfo=datetime.timezone.utc).timestamp()) + 2082844800
    builder.font["head"].created = builder.font["head"].modified = created
    builder.font.recalcTimestamp = False
    output = io.BytesIO()
    builder.font.save(output)
    return output.getvalue()


def install_font(path):
    data = font_bytes()
    if path.exists() and path.read_bytes() == data:
        return
    path.parent.mkdir(parents=True, exist_ok=True)
    with tempfile.NamedTemporaryFile(dir=path.parent, delete=False) as handle:
        temporary = Path(handle.name)
        try:
            handle.write(data)
            handle.flush()
            temporary.chmod(0o644)
            os.replace(temporary, path)
        finally:
            temporary.unlink(missing_ok=True)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", type=Path, default=DESTINATION)
    args = parser.parse_args()
    install_font(args.output.expanduser())
    print(f"Triangle font installed: {args.output}")


if __name__ == "__main__":
    main()
